application.ssh.promptforpassphrase=false
application.ssh.passphrase=${SSH_PASSPHRASE}

# H2 Console (optional, for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.flywaydb=DEBUG
logging.level.com.snjdigitalsolutions=DEBUG
